repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: pretty-format-json
        exclude: (\.ipynb|devcontainer.json)$
        args:
        - --autofix
        - --no-sort-keys
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-added-large-files
        args: [--maxkb=20480]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt
        language: system
        types: [rust]
        pass_filenames: false

  - repo: local
    hooks:
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy
        language: system
        types: [rust]
        pass_filenames: false
